### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by a-wertheim** [Tucsky/aggr#108]
Hi Tucsky, love the site. Curious, is it possible to plot the price by trade rather than by second. In this case the graph would update at the velocity of how quickly each trade (above a determined threshold) comes in. Let me know your thoughts/if this is possible.

Thanks!

**Comment by Tucsky** [comment]
Like a tick chart ?

You can enter '100t' so the chart add a new bar every 100 trades
However if you have aggregation enabled (in the main settings, says 1000ms) it may NOT be as accurate since it will feed the chart aggregated trades and some may contain more than 100 in it so be careful with that

![tick-aggregation-comparison](https://user-images.githubusercontent.com/5738336/139534211-78544517-444c-4df6-a528-de1d25c86b89.gif)

for performance aggregation happens on the background and not at the panes level so we can't have a chart NOT aggregating trades and a feed having aggregation on

**Comment by a-wertheim** [comment]
Yeah this is exactly what I was referring to. Thanks. Lots of settings to play around with. This is really a great site
