### ISSUE TITLE
Adding Indicators

### ISSUE THREAD

**Issue by lmvdz** [Tucsky/aggr#2]
Hi @Tucsky, First off I'd like to say great work!

took a look at beta.aggr.trade ✅
was wondering on how to add a linear regression channel to the chart.
https://www.tradingview.com/scripts/linearregression/
https://www.tradingview.com/script/2YfiGsO0-Envious-Linear-Regression-Trend/

I added "linreg" to seriesBuilder, defaultSeries, seriesUtils
But I am not sure what to do next :/

defaultSeries

```js
linreg: {
    type: 'line',
    input: 'linreg(bar, options)',
    options: {
      source: 'close',
      color: 'rgba(0, 0, 250, 0.5)',
      count: 100,
      upper_deviation: 2,
      lower_deviation: -2,
      use_upper_deviation: true,
      use_lower_deviation: true,
      style: {
        base: {
          color: 'rgba(244, 67, 54, .18)',
          thickness: 1
        },
        up: {
          color: '#1976D2',
          thickness: 1
        },
        down: {
          color: '#1976D2',
          thickness: 1
        },
        pearsonsR: true,
        extendLines: true
      }
    }
  }
```

seriesUtils:

```js
export function linreg(memory, value) {
  const x = memory.points.length
  const y = value.close
  memory.output = {
    x: x,
    y: y,
    xy: x * y,
    xSquared: x * x
  }
  console.log(memory['length'].count, memory.points.length)
  if (memory['length'].count > memory.points.length) {
    return null
  } else {
    let sumY, sumX, sumXSquared, sumXY
    memory.points.slice(memory.points.length - 100).forEach(point => {
      sumX += point.x
      sumY += point.y
      sumXY += point.xy
      sumXSquared += point.xSquared
    })
    const m = (memory['length'].count * sumXY - sumX * sumY) / (memory['length'].count * sumXSquared - sumX * sumX)
    const b = (sumY - m * sumX) / memory['length'].count
    return m * x + b
  }
}
```

**Comment by Tucsky** [comment]
Thank you for having a look! 

As you see it is very very simple scripting and wont allow crazy charting but it's a start...

The thing is **One script can only output a single line**, or a single bar chart etc. So the indic you linked that look like a channel is impossible with this app, mostly because of the underlying charting tool (https://github.com/tradingview/lightweight-charts from tradingview) doesn't support programmatic trendlines, or channels (cannot *fill* between two lines), shapes like rectangles etc. 
Would need to fork that library and add thoses extra features.

What can be done for now is do one serie for top of channel, one for bottom, wont look super pretty but might get the job done 🤷🏼‍♂️ 

![image](https://user-images.githubusercontent.com/5738336/119557539-9b214d00-bda0-11eb-8d92-52129ac63ad6.png)

in the script
```
close(100) = $price.close,
linreg(#close)
```

- `close(100)` create the var "close" with the output.close of another serie (price) and will contain last 100 values
- `linreg(#close)` use a `#` before the var name to reference full "close" array instead of last value

I don't like the current linreg implementation for now as it loop through all values on each updates... Will change later to calculate only for last bar

**Comment by Tucsky** [comment]
https://github.com/tradingview/lightweight-charts/compare/master...mastermobin:cloud-area-chart 
There is more, apparently this guy have successfully added the cloudarea serie type to the library. We might want to replace our lib with the fork if we can confirm that it works without any counterpart on the other serie types / overall performance

If that's the case and it is added, I will add the plot functions to the scripting api
`line(value)`
`candlestick(open, high, low, close)` or `candlestick(bar)`
`bar(open, high, low, close)`
`histogram(value)`
`area(value)`
`cloudarea(high, low)`

each would take pinescript like options (only executed at the creation of serie, except for color passed to histogram) probably easier for parsing, injecting in tv serie api and remove thoses from runtime script
`line(high, low, higherColor=red, lowerColor=blue)`
`cloudarea(high, low, higherColor=red, lowerColor=blue)`

during runtime this syntax would be transformed into
`output.cloudarea_*uniqueserieid* = {higherValue: high, lowerValue: low}`

and later
`level(value)` 
which would create a set of independant lines binded to the serie scale, could be usefull for programmatic fibonnaci levels etc

**Comment by lmvdz** [comment]
I would have to stare at a lot of code/math to figure out how to get that linreg working, unfortunately I don't have a lot of time to get that done. Perhaps in the future I will be able to come back to this and try my hand at it again.

I appreciate the research you've done for this.

Once again great project!!!!!!

**Comment by Tucsky** [comment]
Closing this for now, of course new issue regarding indicator / built in chart functions are welcome :)

**Comment by lmvdz** [comment]
Hey I found this lib, decided to open this up again since we were talking about the custom lib for cloudarea
https://github.com/tvjsx/trading-vue-js

**Comment by Tucsky** [comment]
Thanks, I know the lib and use it in another project. It's pretty good and offer many drawing which is great but not lightweight enough for this aggr.trade

For cloud area I used this fork https://github.com/tradingview/lightweight-charts/compare/master...mastermobin:cloud-area-chart and it is now available in the v3 

in the indicator script :
`plotcloudarea(*low value*, *high value*)`
