### ISSUE TITLE
Embedded website render error

### ISSUE THREAD

**Issue by VanessaE** [Tucsky/aggr#210]
* I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
* I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
* I documented the issue with screenshots
* I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

I have https://market24hclock.com/?set_theme=dark docked into a "website" pane in v3.aggr.trade.  However, the clock renders in light mode, not dark mode, as though the bit after "?" in the URL is being discarded.

![image](https://user-images.githubusercontent.com/1733537/165377557-ad838045-0f2b-441c-9a43-3c8db1564169.png)

I see only two entries in the browser's console related to the page in question:

![image](https://user-images.githubusercontent.com/1733537/165376825-1fa8774d-9b7b-4e4a-b404-e93a364cbab4.png)
![image](https://user-images.githubusercontent.com/1733537/165377069-aa10ae27-2f94-4878-bb33-40edfe8df1b1.png)

My database file:  [aggr-lrnm.txt](https://github.com/Tucsky/aggr/files/8566269/aggr-lrnm.txt)

### Steps to reproduce

Just create a layout, add a "website" pane, and put the above URL in.

**Comment by adeacetis** [comment]
Hello,

I have tested your issue and I could reproduce the issue in production. In my local dev instance, the clock appears black as it should.

Searching why.

**Comment by adeacetis** [comment]
Hello,

I think I have a lead on why it's happening.

The clock script takes the theme attribute from a cookie it saved on your machine. The problem is that Firefox and Chrome/Edge have stricter CRSF policies than Firefox - they changed it around 2020.

Read on here: https://stackoverflow.com/a/45095345

Normally, the site editor should set the cookie parameters on his end. However, you can edit manually the cookie in the developer console (in Chrome ) - still need to test if this persists. Just make sure that the theme cookie has `Secure` set to true (checkbox) and `SameSite` set to "None". If you delete the cookie, you'll have to redo it again.

1) Open the developer console
2) Under Storage > Cookies select the market24clock domain and change the values directly in the columns like so:

![image](https://github.com/Tucsky/aggr/assets/20586054/1499950a-a32c-47b1-9245-7880df9322d5)

Results on Chrome 114:

![image](https://github.com/Tucsky/aggr/assets/20586054/aa78e68d-6d86-4b1c-b367-542ce541f3a3)

In Edge 114 - the problem is different:

The cookie isn't even added to the browser. So, I added it manually and it worked. It's definitely not a problem specific to Aggr, but I am glad I found out the problem wasn't related to our code.
![image](https://github.com/Tucsky/aggr/assets/20586054/a409e838-65b1-462b-b929-78036db1037d)

Close the issue if this is resolved.

**Comment by VanessaE** [comment]
Well manually editing and adding a cookie as you describe is simply unworkable -- I'll never remember that, and besides, it's the browser's job to do that :stuck_out_tongue: 

It's sufficient to just switch the pane to "inverted" mode -- which did not exist when I originally filed this issue.  The colors may be somewhat "wrong" but it still achieves the desired effect.

**Comment by adeacetis** [comment]
I agree with you, although that's the best we could do. I already wrote down to Market24hclock on Twitter asking if they were willing to change the cookie parameters. That's all I can do.

I learned something while helping you out. All is not lost. :)

Have a good day.
