### ISSUE TITLE
New Big Exchanges Perp/Spot

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#217]
Please Add bitget and Kucoin to V3 aggr 🙏

**Comment by Tucsky** [comment]
imma add kucoin

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/168683164-d5f8945e-7c41-4064-a630-dd5058c3bac1.png)

Turns out Kucoin is not allowing ws connection from the browser, even for public market data
Pretty disappointing as I really wanted it to see it on aggr, since kucoin at least wouldn't delist popular coins

We tried 🤷🏼‍♂️
