### ISSUE TITLE
Last 1H btc candle showing wrong colour/level

### ISSUE THREAD

**Issue by dpopov7** [Tucsky/aggr#225]
Thanks for reporting an issue, please review the task list below before submitting the issue :

- [ ] I have attached [an export of my aggr database]
[aggr-a9d9.txt](https://github.com/Tucsky/aggr/files/8837484/aggr-a9d9.txt)
 in the issue
- [ ] I documented the issue with screenshots 
<img width="1431" alt="Screenshot 2022-06-04 at 1 30 41 PM" src="https://user-images.githubusercontent.com/105077493/171995560-192def6a-7a7e-4d4c-8c20-b05874170719.png">
<img width="1440" alt="Screenshot 2022-06-04 at 1 37 46 PM" src="https://user-images.githubusercontent.com/105077493/171995571-2163c5dd-5236-42dd-931a-29d8ae248407.png">

- [ ] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

Hi, 

the last 1H candle in BTCUSD is not showing correctly. In all exchanges it shows green, in aggr shows red and it does not move. If I restart the page it shows the correct value and colour but after a few secs it changes to what you see in the photo and it doesn't move.

### Steps to reproduce

(Preferably from a clean environment / incognito mode)
1. TODO
2. TODO
3. TODO
...

**Comment by Tucsky** [comment]
Thank for the report @dpopov7 
for some reason my server did not received anything for FTX:BTC-PERP since about 1.5days...
So on my server the FTX btc perp was stuck at 30.6k but when you load the app it start pulling realtime data from exchange so ftx price goes straight to it's normal price (few secs after reload), bringing the average down (the red candle you saw)

No idea why FTX stopped sending data for this one tho :/

**Comment by Tucsky** [comment]
Last month server updated fixed all data issue it seems (or maybe the volume is just too low 🤔 ) 
Also markets are now monitored individually which should fix this issue
