### ISSUE TITLE
aggr.trade is down

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#234]
Hi yesterday 6-8h was offlina v3 aggrs. Now there is the same problem that it is impossible to enter the website.

**Comment by Tucsky** [comment]
Hello, thanks for the heads up!

Our hosting provider OVH is having outage problems on our zone since yesterday (seems to be back now, we are still working in filling the holes in the data tho)

If the main server is down (aggr.trade) use this mirror : https://tucsky.github.io/aggr there just won't be any historical data until main server come back

**Comment by Knf69** [comment]
It has now returned to normal and is working. Thanks
