### ISSUE TITLE
highest / lowest functions not working correctly with variable vs literal as second argument

### ISSUE THREAD

**Issue by lahomagit** [Tucsky/aggr#239]
Calling the `highest` (or `lowest`) functions produces different results when called with a variable vs a literal as the second argument.

For example this indicator code:

```
numbars = 4
console.log("highest numbars: " + highest($price.high,numbars))
console.log("highest actual: " + highest($price.high,4))
```

Produces this console output (tested on local aggr instance as well as official site with & without incognito):
```
highest numbars: 1.3510888888888888
highest actual: 1.3533166666666667
```

It seems like, when called with a variable as second argument, the function behaves as though the second argument is `1` (outputting the high of the current bar). Am I missing something?

**Comment by Tucsky** [comment]
because the length argument can't change during script execution you have to use a number or option from the indicator and not a variable
`highest($price.high,4)` works
`highest($price.high,options.length)` works as well
`highest($price.high, numbars)` don't work because during build stage of indi, it doesn't know what numbars is

ofc in your example it's clear that it's 4, but it could change since it's a var
