### ISSUE TITLE
Bitcoin chart goes out of scale over time

### ISSUE THREAD

**Issue by VanessaE** [Tucsky/aggr#246]
(using Google Chrome 105.0.5195.125 on Debian "buster" 11.5)

### Describe the issue

After some time, the scale of the candles on aggr.trade goes out of sync with the real prices on an exchange.  That is to say, you might see a rise of 500 on the exchange, but aggr might only show 200 or so rise.

Expand that over time and it'll look like the scale of the graph itself changes relative to the price scale as it ages, but if you reload the page, the graph will be re-rendered properly.  In fact, it seems to be enough to simply change to another candle timeframe, wait for it to load, and then switch back.

For example, here's BTC/USD as shown on my browser when I started writing this issue, after being open and idle for a few hours:

![image](https://user-images.githubusercontent.com/1733537/191760451-5238e554-21d1-4293-b9cc-ce4a8869a355.png)

Here it is on my favored exchange (note: I had to edit this image to remove something sensitive):

![image](https://user-images.githubusercontent.com/1733537/191768446-95c67fed-c4d2-44c3-9a86-f769a7ad934d.png)

Now, I reload the aggr.trade web page, and notice how the apparent scale of the most recent candles over there on the right has changed relative to the older data:

![image](https://user-images.githubusercontent.com/1733537/191760983-d43220d7-707e-4d09-8fd6-6900e21e7f2c.png)

Here's a closeup showing the change:

![image](https://user-images.githubusercontent.com/1733537/191762285-877eb41e-70d7-467b-bb43-5834eaf520e9.png)

(all images above are 15 minute candle timeframe)

Of course one must ignore the very last candle, but as you can see, the relative vertical positions and/or sizes of the several candles preceding it have changed, even though nothing else about the page has changed.

I haven't noticed how far the scaling issue will go, but I do know it can affect at least the most recent few hours' worth of candles.

### Steps to reproduce

Just leave the aggr page open for a while, compare the graph to an exchange, then reload aggr and see the difference.

**Comment by VanessaE** [comment]
(oops, hit enter at the wrong moment, please see issue on github for the full report)

**Comment by VanessaE** [comment]
Turns out my charts had "Always normalize mean" enabled.  No idea how that happened, as I had been explicitly avoiding that setting (since the tooltip mentions it'll create inaccurate prices).

**Comment by Tucsky** [comment]
yeah that's the one! you most likely have a pair in your selection that don't have historical data

That option is enabled by default **now** **but wasn't before feb of this year**

It is only usefull when mixing pairs (diff assets) on the same chart like creating "indexes", <u>the realtime price is the right one</u>.
for pairs that don't have historical data, it rerender the whole chart as soon as the first trade is received for that pair and re-attribute that trade price for previous candle avoiding getting those huge cliffs on the realtime chart


For exemple this is 3 charts with btcusdt and btcusdc on the binance exchange
the while lines are BINANCE:btcusdt (full data) and BINANCE:btcusdc (realtime only)

![image](https://user-images.githubusercontent.com/5738336/192370199-1cf883b2-3bef-4cfc-9344-1d80457e4c45.png)
This was drawn using historical data only
"Always normalize mean" is ON
Notice the while line (btcusdc is the same price that whole chart, to ensure all pairs on that chart have at least a price)
<br>

![image](https://user-images.githubusercontent.com/5738336/192370690-0554ed3e-448c-42f5-b877-a9c9a20ad058.png)
Again this was drawn using historical data only
but "Always normalize mean" is OFF
No white line for btcusdc which have no historical data, no price, average (candlestick) is calculated using btcusdt only
<br>

![image](https://user-images.githubusercontent.com/5738336/192369785-3ebc1e26-ddac-4040-9528-cd81d034f5ad.png)
This one was drawn using realtime data. I just let it run for a while
"Always normalize mean" is ON

Hate this option because 99% don't need it and it's tricky to explain, in the end it's just data issue because if I had data since forever for all pairs I wouldn't have to implement it 🤔 Wish I could figure a better name for it
