### ISSUE TITLE
Adding Uniswap to follow HEX trades

### ISSUE THREAD

**Issue by aldogrillo** [Tucsky/aggr#255]
I would like to track the token HEX. Uniswap has a larger trading volume then Poloniex but I do not see that you have the trading feed from Uniswap. WIll Uniswap be adding soon?

**Comment by adeacetis** [comment]
Hello,

UNISWAP has been added to the available exchange since you requested it but you need to enable it to make it visible.

To do so:
1) You need to open the settings menu from the context - bottom right green button;
![image](https://github.com/Tucsky/aggr/assets/20586054/c596a680-ab18-45ff-86b2-a073a7226c9d)

2) A floating window should appear. Under Exchange section, you should see UNISWAP the name crossed through.

![image](https://github.com/Tucsky/aggr/assets/20586054/6099280c-342c-40ee-b375-4abe1acd996e)

3) Click on the name to enable it.

4) Open the connection panel, you should see UNISWAP on your left. Add a new pair as you would do normally.

There are no historical data for UNISWAP pairs right now. This is still experimental, hence it is disabled by default. We may add them when we'll scale our infra.

Hope it helps.
