### ISSUE TITLE
Donchian indicator bugging

### ISSUE THREAD

**Issue by airbors** [Tucsky/aggr#257]
![image](https://user-images.githubusercontent.com/46748513/197658469-329cd046-0abd-4a7e-ae63-1324061f5171.png)

![image](https://user-images.githubusercontent.com/46748513/197658484-34312e69-89ae-46e9-98bd-fd575d257ddc.png)

Why is it doing this? Could you do a quick fix if possible?

Grateful for your work bro.

Using tick chart if it matters

**Comment by Tucsky** [comment]
This one works for me : 
[indicator_donchian-channel-2.txt](https://github.com/Tucsky/aggr/files/9858491/indicator_donchian-channel-2.txt)

tho not sure what the issue on yours since the code is pretty much the same
You found the bug of the highest lowest which doesnt seem to account the last value, I just replaced with high and low instead of close

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/5738336/197722970-21d4afd3-2266-4208-bd20-4d5be356cb9f.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/5738336/197723056-58c3ff17-eeee-4faa-9f4c-27106f6ab0ac.png">

**Comment by airbors** [comment]
Your indies worked, thanks a lot! It was also because I think I didn't have a well coded price indie, it didn't recognize it. Ur the best bro all the best to you
