### ISSUE TITLE
Kucoin+Poloniex Problem

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#265]
Hello Dad! 
Thanks for adding kucoin/Uniswap
I see that kucoin spot is available visible for adding but there is no kucoin perp btc/eth it. Same Liq Kucoin I don't see it in the options to add either.
Poloniex searching is a problem because it shows all parties btc same Eth there are over 8/9+ pages

**Comment by Knf69** [comment]
@Tucsky

**Comment by Tucsky** [comment]
Yeah I told you I couldn't add kucoin, because unlike all other exchanges you need a token to connect
So I did the test where the server generate the token, and all clients (on v3.aggr, charts.aggr etc) use the same token to connect, since they can't generate their own
And very surprisingly it just seems to works alright
Idk for how long it will work tho, maybe there is a limit (how many IPs allowed on the same token)
But anyway it was a test, now I think imma go ahead and add more pairs and perps for kucoin.

**Comment by Tucsky** [comment]
For poloniex yesterday I noticed that the UI client code was using their depreciated api, they updated it (while ago) and now all the tickers for polo have changed
you have to use POLONIEX:BTC_USDT (new) instead of POLONIEX:USDT_BTC (old)
Didn't quite get what you were saying about poloniex but it might just be that

**Comment by Knf69** [comment]
Ye i understand. Now i see Kucoin Spot btc work good show all. Well, it is a pity that there will not be this Kucoin perp is there a large volume and real what is important.

**Comment by Knf69** [comment]
@Tucsky What do you think about the "Crypto.com" exchange?

**Comment by adeacetis** [comment]
Kucoin API has been added and is available on the https://charts.aggr.trade
