### ISSUE TITLE
add  binance us

### ISSUE THREAD

**Issue by AliShakerdev** [Tucsky/aggr#282]
**Describe the solution you'd like**

Add Binance US feed

**Comment by adeacetis** [comment]
You didn't fill out the bug form adequately. Please fill it as expected as it is confusing for all of us.

**Comment by Tucsky** [comment]
@AliShakerdev  We can use Binance US on the feeds for years now, you might not see it in the list because it's disabled by default (to prevent the client to download / store binance US products for no reason)

Open settings and scroll to the exchanges section, and click on Binance US one time to enable the exchange. Then in the search window you will notice Binance US is visible 
![2023-03-15 19 32 26](https://user-images.githubusercontent.com/5738336/225408696-23a83ce3-bd8c-45aa-96a9-3b85f5060c33.gif)

Historical data for Binance US BTC & ETH was added very recently

Closing now as it seems resolved but feel free to reopen if needed!
