### ISSUE TITLE
Pane names do not disappear

### ISSUE THREAD

**Issue by akenshaw** [Tucsky/aggr#313]
https://imgur.com/a/Rg7mNV1

"Auto hide headers" is enabled. Is this intended? If so, please give us an option to hide them also, like before.

**Comment by adeacetis** [comment]
It's a workaround. Did you remove the functionality? Did you change default behaviou?Top left Pane Headers also don't auto hide on my charts, it used to be tho.From: Tucsky ***@***.***>Sent: Friday, 12 May 2023, 15:54To: Tucsky/aggr ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [Tucsky/aggr] Pane names do not disappear (Issue #313)
One workaround is to set the name to " " so that it won't show

**Comment by Tucsky** [comment]
@adeacetis I needed to see the names without having to hover each panes with the mouse... but also not wanted the header to take their own space on the screen (remain floating above the pane content)
This is especially usefull for chart... I find chart watermark is often disabled or not readable enough 
The header container was also shortened (no more full width header) only name on the left and options on the right, leaving the middle visible and accessible to interaction, this is especially usefull for feeds. Options still get hidden automatically!

It's just a good compromise and that old "auto hide headers" option can be renamed as "floating pane header" option I think :)
