### ISSUE TITLE
API error ( Failed to fetch)

### ISSUE THREAD

**Issue by tjddnjs124** [Tucsky/aggr#69]
the chart cant load saved OHLC API data. Check please :)
![image](https://user-images.githubusercontent.com/26290547/127781262-7f568fe3-8d88-4986-b5a0-f4cf344376db.png)

**Comment by Tucsky** [comment]
No must be just u, we had no down time whatsoever, works for me 🤷🏼‍♂️

**Comment by MrYuto** [comment]
I suggest you try using a VPN or a proxy :(

**Comment by Tucsky** [comment]
I think that bug was due to the selected timeframe not being available as historical data (ex: 1s)
Just added a check to avoid showing this message

Api support following timeframes are 5s 10s 15s 30s 1m 3m 5m 15m 30m 1h 2h 4h 6h 1d
the latest 5000 bars are available for each of them (starting 20/04/20)
