### ISSUE TITLE
BTC History & 21min 

### ISSUE THREAD

**Issue by MA-inv** [Tucsky/aggr#73]
Hi, BTC history seems gone after the new update.

Thanks for the 30min time frame, but any chance we can have 21min back or custom setting?

thanks

**Comment by Tucsky** [comment]
Hello @MA-inv 
Yes clearing the whole db was required in order to use the new 5k bars retention policy across all tf 
**The candles are still being imported at the moment** (takes about 10h lol)

About the 21m and 8h chart I removed those because the candles were incorrectly calculated.
Instead 15s is added as well as 5s, 30min as you saw and 6h.

**Comment by Tucsky** [comment]
> candles were incorrectly calculated.

fixed

> or custom setting

Yes indeed, changing timeframe manually is possible, any timeframe you want
But for the data to be resampled into the desired timeframe it needs to be compatible with it (less and divisible without remainder) 

![2021-08-08 22 04 47](https://user-images.githubusercontent.com/5738336/128644449-fd828fae-1785-489d-a728-b4ae1684171e.gif)

**Comment by MA-inv** [comment]
Thanks, that's awesome, just playing with it now
