### ISSUE TITLE
[Feature] My preset json

### ISSUE THREAD

**Issue by yerb** [Tucsky/aggr#83]
Here is my preset json if anyone wants to use it. Or it can be added as an example preset.
[ptw1_btcusdethusd2.zip](https://github.com/Tucsky/aggr/files/7023562/ptw1_btcusdethusd2.zip)

**Comment by Tucsky** [comment]
I have been using this one

![image](https://user-images.githubusercontent.com/5738336/130490428-6f084961-971c-4189-bb1c-a81e72c7dd63.png)
just make sure your build can handle it as it subscribe to approx 300+ websockets channels + the okokito frame that use a shitload of data

[qw6i_overview.zip](https://github.com/Tucsky/aggr/files/7033799/qw6i_overview.zip)
-simply extract the .json and drop it on the app to import

of course then change the mini charts to your liking, I put the one with historical data because it just better looking (not necessarily trading :)) )

**Comment by yerb** [comment]
Very nice :)

**Comment by Tucsky** [comment]
Alright closing this now
Idk why anyone would share a money making template but if anything discussions section would be more appropriate for this kind of topic
