### ISSUE TITLE
Save and store aggregated trades

### ISSUE THREAD

**Issue by thebitbrine** [Tucsky/aggr#91]
I wanted to log all trades going through aggr and potentially store it in a database for later analysis (or even some ML training)
I've looked through the code but couldn't find the function trades pass through in their final shape, however I've landed on ```pendingTrades``` but I feel like that not the correct function.

If you have any ideas on how this could be done/implemented and what DB can I use,
I would be thankful if you could share it with me.

Thanks in advance.

**Comment by Tucsky** [comment]
This is a client side app that run in the browser, not made for collecting data, just display it in real time...
Instead you should look into server solution that run in the background

https://github.com/Tucsky/aggr-server 
- collect and store the raw trade data
- create ohlc series from the trades
- dispatch aggregated trades through websocket

You could use it as a base : remove the ohlc making part and pass the output of aggregation into the storage solution instead of broadcasting them ;)
